applications/persona/urls.py
from django.contrib import admin
from django.urls import path

from . import views

#  asignamos un argumento <shorname>

app_name = "persona_app"

urlpatterns = [
    path(
        '',
        views.InicioView.as_view(),
        name='inicio'
    ),
    path('listar-todo-empleados/', 
        views.ListAllEmpleados.as_view(),
        name='empleados_all'
    ),
    path('lista-by-area/<shorname>', 
        views.ListByAreaEmpleado.as_view(),
        name='empleados_area'
    ),
    path('lista-empleados-admin/', 
        views.ListaEmpleadosAdmin.as_view(),
        name='empleados_admin'
    ),
    path('lista-by-trabajo/<jobemp>', views.ListByTrabajoEmpleado.as_view()),
    path('buscar-empleado/', views.ListEmpleadosByKword.as_view()),
    path('lista-habilidades-empleado/', views.ListHabilidadesEmpleado.as_view()),
    # <pk> hace referencia a un id interno a recuperar,  tambien se recupera con el nombre del modelo <empleado>
    path('ver-empleado/<pk>', 
        views.EmpleadoDetailView.as_view(),
        name='empleado_detail'
    ),
    path(
        'add-empleado/', 
        views.EmpleadoCreateView.as_view(),
        name='empleado_add'
    ),
    path(
        'success/',
        views.SuccessView.as_view(),
        name='correcto'
     ),
    path(
        'update-empleado/<pk>',
        views.EmpleadoUpdateView.as_view(),
        name='modificar_empleado'
    ),
    path(
        'delete-empleado/<pk>',
        views.EmpleadoDeleteView.as_view(),
        name='eliminar_empleado'
    ),
]

empleado/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings

""" nos ayuda a generar urls staticas para nuestro ficheros multimedias """
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # incluimos la urls de la app departamento
    re_path('', include('applications.departamento.urls')),
    re_path('', include('applications.persona.urls')),
    re_path('', include('applications.home.urls'))
] + static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)

applications/persona/models.py
from django.db import models
from ckeditor.fields import RichTextField

from applications.departamento.models import Departamento

# Create your models here.

class Habilidades(models.Model):
    """ Modelo para tabla de habilidad"""

    habilidad = models.CharField('Habilidad', max_length=50)

    class Meta:
        verbose_name = 'Habilidad'
        verbose_name_plural = "Habilidades Empleados"
    
    def __str__(self):
        return str(self.id) + ' ' + self.habilidad

class Empleado(models.Model):
    """ Modelo para tabla empleado """

    JOB_CHOICES = (
        ('0', 'CONTADOR'),
        ('1', 'ADMINISTRADOR'),
        ('2', 'ECONOMISTA'),
        ('3', 'OTRO'),
    )
    first_name = models.CharField('Nombres', max_length=60)
    last_name = models.CharField('apellidos', max_length=60)
    full_name = models.CharField('Nombre Completo', max_length=120, blank=True)
    job = models.CharField('Trabajo', max_length=1, choices=JOB_CHOICES)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='empleado', blank=True, null=True)
    habilidades = models.ManyToManyField(Habilidades)
    hoja_vida = RichTextField()

    class Meta:
        verbose_name = 'Empleados'
        verbose_name_plural = 'Perfil del empleado'
        ordering = ['-first_name']
        unique_together = ('first_name', 'last_name') 

    def __str__(self):
        return str(self.id) + ' ' + self.first_name + '-' + self.last_name

applications/persona/forms.py
from django import forms

from .models import Empleado

class EmpleadoForm(forms.ModelForm):
     
    class Meta:
        model = Empleado
        fields = (
            'first_name',
            'last_name',
            'job',
            'departamento',
            'avatar',
            'habilidades',
        )
        widgets = {
            'habilidades': forms.CheckboxSelectMultiple()
        }
         

applications/persona/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    TemplateView,
    UpdateView,
    DeleteView
) 
# models
from .models import Empleado
# forms
from .forms import EmpleadoForm

# Create your views here.
class InicioView(TemplateView):
    """ Vista que carga la pagina de inicion"""
    template_name = 'inicio.html'


class ListAllEmpleados(ListView):
    template_name = 'persona/list_all.html'
    # se asigna paginacion en bloques de 4 reg y se crea un objeto 'pag_obj'
    paginate_by = 4
    ordering = 'first_name'
    context_object_name = 'empleados'
    # model = Empleado  -> ya no se necesita el model
    def get_queryset(self):
        # print('************************')
        palabra_clave = self.request.GET.get("kword", '')
        lista = Empleado.objects.filter(
            first_name__icontains=palabra_clave
        )
        return lista


class ListaEmpleadosAdmin(ListView):
    template_name = 'persona/lista_empleados.html'
    # se asigna paginacion en bloques de 10 
    paginate_by = 10
    ordering = 'first_name'
    context_object_name = 'empleados'
    model = Empleado  
    

class ListByAreaEmpleado(ListView):
    """ Lista empleados de un area """
    template_name = 'persona/list_by_area.html'
    context_object_name = 'empleados'

    # queryset = Empleado.objects.filter(
    #     departamento__shor_name = 'Mantenimiento'

    def get_queryset(self):
        area = self.kwargs['shorname']
        lista = Empleado.objects.filter(
            departamento__shor_name = area
        )
        return lista


class ListByTrabajoEmpleado(ListView):
    """ Lista empleados de un area asigna argumento"""
    template_name = 'persona/list_by_trabajo.html'

    def get_queryset(self):
        area = self.kwargs['jobemp']
        lista = Empleado.objects.filter(
            job = area
        )
        return lista


class ListEmpleadosByKword(ListView):
    """ Lista de empleado por palabra clave """
    template_name = 'persona/by_kword.html'
    context_object_name = 'empleados'

    def get_queryset(self):
        print('************************')
        palabra_clave = self.request.GET.get("kword", '')
        lista = Empleado.objects.filter(
            first_name=palabra_clave
        )
        return lista


class ListHabilidadesEmpleado(ListView):
    template_name = 'persona/habilidades.html'
    context_object_name = 'habilidades'

    def get_queryset(self):
        empleado = Empleado.objects.get(id=3)
        # Lista de la tabla empleado todas las habilidades
        return empleado.habilidades.all()

# 1. - Lista todos los empleados de la empresa
# 2. - Listar todos los empleados que pertenecen a un area de la empresa
# 3. - Listar empleados por trabajao
# 4. - Listar los empleados por palabras clave
# 5. - Listar habilidades de un empleado

class EmpleadoDetailView(DetailView):
    model = Empleado
    # <pk> hace referencia a un id interno
    template_name = 'persona/detail_empleado.html'

    # añadimos el get_context_data para añadir un texto al titulo definido en el template
    def get_context_data(self, **kwargs):
        context = super(EmpleadoDetailView, self).get_context_data(**kwargs)
        context['titulo'] = 'Empleado del mes'
        return context


class SuccessView(TemplateView):
    template_name =  'persona/success.html'


#class EmpleadoCreateView(CreateView):
#    model = Empleado
#    template_name = 'persona/add.html'
#    # fields = ('__all__') -> muestra todos los campos
#    fields = [
#        'first_name',
#        'last_name',
#        'job',
#        'departamento',
#        'avatar',
#        'habilidades',
#    ]
#    success_url = reverse_lazy('persona_app:empleado_admin')

# este form EmpleadoForm lo asiganamos a esta vista y reemplaza la anterior CreateView cambiamos la forma de pintar forms
class EmpleadoCreateView(CreateView):
    model = Empleado
    template_name = 'persona/add.html'
    form_class = EmpleadoForm 
    success_url = reverse_lazy('persona_app:empleado_admin')

    def form_valid(self, form):
        empleado = form.save(commit=False)
        # print(empleado) --> para comprobar en prompt que se graba el reg.
        empleado.full_name = empleado.first_name + ' ' + empleado.last_name
        empleado.save()
        return super(EmpleadoCreateView, self).form_valid(form)


class EmpleadoUpdateView(UpdateView):
    template_name = 'persona/update.html'
    model = Empleado
    fields = [
        'first_name',
        'last_name',
        'job',
        'departamento',
        'habilidades',
    ]
    success_url = reverse_lazy('persona_app:empleados_admin')

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        print('********METODO POST*********')
        print('***************************')
        print(request.POST)
        print(request.POST['last_name'])
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        print('********METODO form_valid *********')
        print('***************************')
        return super(EmpleadoUpdateView, self).form_valid(form)


class EmpleadoDeleteView(DeleteView):
    template_name = 'persona/delete.html'
    model = Empleado
    success_url = reverse_lazy('persona_app:empleados_admin')  

templates/persona/add.html
{% extends 'base.html' %}

{% block title %}
    Agregar Empleados
{% endblock title %}

{% block content %}

{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <h5 class="cell">Registrar empleado</h5>
        <form class="cell grid-x grid-margin-x" method="POST" enctype="multipart/form-data">{% csrf_token %}
            <div class="medium-6 cell">
                <label>Nombres:
                    {{form.first_name}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Apellidos:
                    {{form.last_name}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Trabajo:
                    {{form.job}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Departamento:
                    {{form.departamento}}
                </label>
            </div>
            <div class="medium-12 cell">
                <label>Habilidades:
                    {{form.habilidades}}
                </label>
            </div>
            <div class="medium-12 cell">
                <label>Foto:
                    {{form.avatar}}
                </label>
            </div>
            <div class="cell medium-12">
                <button class="submit" class="success button">Guardar</button>
            </div>
        </form>
    </div>
</div>

{% endblock content %}
    
    

 

templates/persona/by_kword.html
<h1>Buscar empleados por palabra clave</h1>
<form method = "GET">{% csrf_token %}
    <input type ="text" id="kword" name="kword" placeholder="ingrese nombre aqui">
    <button type="submit">Buscar</button>
</form>

<h3>Lista de resultados</h3>
<ul>
    {% for e in empleados %}
        <li>{{e}}</li>
    {% endfor %}
</ul>

templates/persona/delete.html
{% extends 'base.html' %}


{% block title %}
    Eliminar Empleado
{% endblock title %}


{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Eliminar Empleado: {{ object.first_name }}</h1>
        <form class="cell" method="POST">{% csrf_token %}
            <div class="callout secondary">
                <h5>Desea eliminar este empleado?</h5>
                <button type="submit" class="alert button">Confirmar</button>
            </div>
        </form>
    </div>
</div>

{% endblock content %}
    

templates/persona/detail_empleado.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    {{ object.full_name }}
{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}

<!-- añadimos un texto al final del titulo con {{ titulo }} -->
<!-- <h1>Detalle de un empleado {{ titulo }}</h1>-->
<!-- recuperamos los reg. con 'object' o con el nombre del modelo 'empleado'-->
<!-- {{ object }} es el contexto que manda por defecto el detailView-->

<div class="grid-container">
    <div class="grid-x grid-margin-x align-center">
        <div class="cell large-4 card" style="width: 300px; margin-top: 10px;">
            <div class="card-divider">
                <!-- nos recupera el siguiente valor del diccionario de atributo choice -->
              {{ empleado.get_job_display }}
            </div>
            
            {% if empleado.avatar %}
                <img src="{{ empleado.avatar.url }}">
            {% else %}
                <img src="{% static 'img/car.webp' %}">
            {% endif %}
            <div class="card-section">
                <h6>{{ empleado.full_name }}</h6>
                <p>{{ empleado.last_name }}</p>
                <p>{{ empleado.departamento.shor_name }}</p>
                <p><span class="label">Habilidades</span></p>
                <ul class="vertical menu">
                    {% for h in empleado.habilidades.all %}
                        <li>{{ h.habilidad }}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>
    
{% endblock content %}

templates/persona/habilidades.html
<h1>Lista de habilidades por empleado</h1>
<ul>
    {% for h in habilidades %}
    <li>{{ h }}</li>

    {% endfor %}
</ul>

templates/persona/list_all.html
<!-- heredamos base.html --> 
{% extends 'base.html' %}

<!-- para que muestre el contenido de body redefinimos el bloque content --> 
{% block content %}
<!-- hace el llamado de la cabecera include --> 
{% include 'includes/header.html' %}
<!-- se crean 3 bloques con div -->
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista de Empleados</h1>
        <form class="cell grid-x grid-margin-x" method="GET">{% csrf_token %}
            <div class="cell large-7">
                <input text="text" id="kword" name="kword" placeholder="burcar empleado">
            </div>
            <div class="cell large-2">
                <button type="submit" class="success button">Buscar</button>
            </div>
        </form>
        <div class="cell">
            <table>
                <thead>
                  <tr>
                    <th width="200">ID</th>
                    <th>NOMBRES</th>
                    <th width="150">APELLIDOS</th>
                    <th width="150">DEPARTAMENTO</th>
                    <th width="150">ACCION</th>
                  </tr>
                </thead>
                <tbody>
                    <!-- Itera empleado con el bucle for y in object_list reemplazo por objeto empleados-->
                    {% for e in empleados %}
                    <tr>
                        <td>{{ e.id }}</td>
                        <td>{{ e.first_name }}</td>
                        <td>{{ e.last_name }}</td>
                        <td>{{ e.departamento }}</td>
                        <td><a class="button warning" href="{% url 'persona_app:empleado_detail' e.id %}">Ver</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="cell">
            {% if is_paginated %}
            <nav aria-label="Pagination">
                <ul class="pagination">
                    {%  if page_obj.has_previous %}
                    <li class="pagination-previous">
                        <a href="?page={{page_obj.previous_page_number}}">Atras</a>
                    </li>
                    {% endif %}

                    {% for pagina in paginator.page_range %}
                    
                    <!-- pagina trae el nuero y page_obj es la pagina actual -->
                    {% ifequal pagina page_obj.number%} 
                    <li class="current"><span class="show-for-sr">You're on page</span>{{ pagina }}</li>
                    {% else %}
                    <li><a href="?page={{pagina}}">{{ pagina }}</a></li>  
                    {% endifequal %}
                    {% endfor %}
                    
                    {%  if page_obj.has_next %}
                    <li class="pagination-next">
                        <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
            {% endif %}
        </div>
        
    </div>
</div>
{% endblock content %}

templates/persona/list_by_area.html
{% extends 'base.html' %}

{% block content %}
<!-- hace el llamado de la cabecera include --> 
    {% include 'includes/header.html' %}

    <div class='grid-container'>
        <div class="grid-x">
            <div class="cell">Empleados por Area:</div>
            <div class="cell">
                <table>
                    <thead>
                      <tr>
                        <th width="200">ID</th>
                        <th>NOMBRES</th>
                        <th width="150">APELLIDOS</th>
                        <th width="150">DEPARTAMENTO</th>
                        <th width="150">ACCION</th>
                      </tr>
                    </thead>
                    <tbody>
                        <!-- Itera empleado con el bucle for y in object_list reemplazo por objeto empleados-->
                        {% for e in empleados %}
                        <tr>
                            <td>{{ e.id }}</td>
                            <td>{{ e.first_name }}</td>
                            <td>{{ e.last_name }}</td>
                            <td>{{ e.departamento }}</td>
                            <td><a class="button warning" href="{% url 'persona_app:empleado_detail' e.id %}">Ver</a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock content %}

<h1>Lista de empleados por departamento</h1>


<ul>
    {% for e in object_list %}
    
        <li>{{ e }} </li>
    {% endfor %}
     
</ul>

templates/persona/list_by_trabajo.html
<h1>Listado de empleados por trabajo</h1>

<ul>
    {% for e in object_list %}
    
        <li>{{ e }} </li>
    {% endfor %}
     
</ul>

templates/persona/lista_empleados.html
<!-- heredamos base.html --> 
{% extends 'base.html' %}

<!-- para que muestre el contenido de body redefinimos el bloque content --> 
{% block content %}
<!-- hace el llamado de la cabecera include --> 
{% include 'includes/header.html' %}
<!-- se crean 3 bloques con div -->
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista de Empleados</h1>
        <div class="cell">
            <table>
                <thead>
                  <tr>
                    <th width="200">ID</th>
                    <th>NOMBRES</th>
                    <th width="150">APELLIDOS</th>
                    <th width="150">DEPARTAMENTO</th>
                    <th width="150">ACCION</th>
                  </tr>
                </thead>
                <tbody>
                    <!-- Itera empleado con el bucle for y in object_list reemplazo por objeto empleados-->
                    {% for e in empleados %}
                    <tr>
                        <td>{{ e.id }}</td>
                        <td>{{ e.first_name }}</td>
                        <td>{{ e.last_name }}</td>
                        <td>{{ e.departamento }}</td>
                        <td>
                            <a class="button success" href="{% url 'persona_app:modificar_empleado' e.id %}">Editar</a>
                        </td>
                        <td>
                            <a class="button alert" href="{% url 'persona_app:eliminar_empleado' e.id %}">Eliminar</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="cell">
            {% if is_paginated %}
            <nav aria-label="Pagination">
                <ul class="pagination">
                    {%  if page_obj.has_previous %}
                    <li class="pagination-previous">
                        <a href="?page={{page_obj.previous_page_number}}">Atras</a>
                    </li>
                    {% endif %}

                    {% for pagina in paginator.page_range %}
                    
                    <!-- pagina trae el nuero y page_obj es la pagina actual -->
                    {% ifequal pagina page_obj.number%} 
                    <li class="current"><span class="show-for-sr">You're on page</span>{{ pagina }}</li>
                    {% else %}
                    <li><a href="?page={{pagina}}">{{ pagina }}</a></li>  
                    {% endifequal %}
                    {% endfor %}
                    
                    {%  if page_obj.has_next %}
                    <li class="pagination-next">
                        <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
            {% endif %}
        </div>
        
    </div>
</div>
{% endblock content %}

templates/persona/success.html
<h1>Felicitaciones! se guardo correctamente el empleado</h1>

templates/persona/update.html
{% extends 'base.html' %}


{% block title %}
    Editar Empleado
{% endblock title %}


{% block content  %}

{% include 'includes/header.html' %}

<div class='grid-container'>
    <div class="grid-x">
        <h4 class="cell">
            Modificar Empleado
        </h4>
        <div class="cell">
            <!-- token para enviar datos al formulario, cell large-6 para que lo divida en columnas-->
            <form class="grid-x grid-margin-x callout success" method="POST">{% csrf_token %}
                <div class="cell large-6">
                    <label>Nombres:
                        {{ form.first_name }}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Apellidos:
                        {{ form.last_name }}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Trabajo:
                        {{ form.job }}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Area:
                        {{ form.departamento }}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Habilidades extra:
                        {{ form.habilidades }}
                    </label>
                </div>
                <div class="cell">
                    <button type="submit" class="success button">Guardar</button>
                </div>
            </form>
        </div>
    </div>
</div>
    
{% endblock content  %}
    