applications/departamento/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "departamento_app"

# prueba
# def DesdeApps(self):
#    print("-----------Desde la Apps Departamento-------------")
# urlpatterns = [
#    path('departamento', DesdeApps),
#]

urlpatterns = [
    path('departamento-lista/', 
        views.DepartamentoListView.as_view(), 
        name='departamento_list'
    ),
    path('new-departamento/', views.NewDepartamentoView.as_view(), name='nuevo_departamento'),
]

applications/persona/urls.py
from django.contrib import admin
from django.urls import path

from . import views

#  asignamos un argumento <shorname>

app_name = "persona_app"

urlpatterns = [
    path(
        '',
        views.InicioView.as_view(),
        name='inicio'
    ),
    path('listar-todo-empleados/', 
        views.ListAllEmpleados.as_view(),
        name='empleados_all'
    ),
    path('lista-by-area/<shorname>', 
        views.ListByAreaEmpleado.as_view(),
        name='empleados_area'
    ),
    path('lista-empleados-admin/', 
        views.ListaEmpleadosAdmin.as_view(),
        name='empleados_admin'
    ),
    path('lista-by-trabajo/<jobemp>', views.ListByTrabajoEmpleado.as_view()),
    path('buscar-empleado/', views.ListEmpleadosByKword.as_view()),
    path('lista-habilidades-empleado/', views.ListHabilidadesEmpleado.as_view()),
    # <pk> hace referencia a un id interno a recuperar,  tambien se recupera con el nombre del modelo <empleado>
    path('ver-empleado/<pk>', 
        views.EmpleadoDetailView.as_view(),
        name='empleado_detail'
    ),
    path(
        'add-empleado/', 
        views.EmpleadoCreateView.as_view(),
        name='empleado_add'
    ),
    path(
        'success/',
        views.SuccessView.as_view(),
        name='correcto'
     ),
    path(
        'update-empleado/<pk>',
        views.EmpleadoUpdateView.as_view(),
        name='modificar_empleado'
    ),
    path(
        'delete-empleado/<pk>',
        views.EmpleadoDeleteView.as_view(),
        name='eliminar_empleado'
    ),
]

empleado/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings

""" nos ayuda a generar urls staticas para nuestro ficheros multimedias """
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # incluimos la urls de la app departamento
    re_path('', include('applications.departamento.urls')),
    re_path('', include('applications.persona.urls')),
    re_path('', include('applications.home.urls'))
] + static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)

applications/departamento/models.py
from django.db import models

# Create your models here, blank_True -> el campo permite espacios o null=True
# str(self.id) el id es entero str permite un string
# editable=False -> bloquea el uso de ese campo

class Departamento(models.Model):
    name = models.CharField('Nombre', max_length=50, blank=True, null=True)
    shor_name = models.CharField('Nombre Corto', max_length=20, unique=True)
    anulate = models.BooleanField('Anulado', default=False)

    class Meta:
        verbose_name = 'Mi Departamento'
        verbose_name_plural = 'Areas de la empresa'
        ordering = ['-name']
        unique_together = ('name', 'shor_name') 

    def __str__(self):
        return str(self.id) + ' ' + self.name + '-' + self.shor_name

applications/departamento/forms.py
from django import forms

# Formulario no vinculado con ningun modelo

class NewDepartamentoForm(forms.Form):
    nombre = forms.CharField(max_length=50)
    apellidos = forms.CharField(max_length=50)
    departamento = forms.CharField(max_length=50)
    shorname = forms.CharField(max_length=50)

applications/departamento/views.py
from django.shortcuts import render
# importamos
from django.views.generic.edit import FormView
from applications.persona.models import Empleado 
from .models import Departamento
from django.views.generic import ListView

# no necesitamos especificar un modelo pero el form si necesita sobreescribir la funcion form_valid

from .forms import NewDepartamentoForm

class DepartamentoListView(ListView):
    template_name = "departamento/lista.html"
    model = Departamento
    context_object_name = "departamentos"
    


class NewDepartamentoView(FormView):
    template_name = 'departamento/new_departamento.html'
    form_class = NewDepartamentoForm
    success_url = '/'

    def form_valid(self,form):
        print('*********estamos en el form_valid **********')

        # Guardamos departamento
        depa = Departamento(
            name=form.cleaned_data['departamento'],
            shor_name=form.cleaned_data['shorname']
        )
        depa.save()

        # Guardamos empleado
        nombre = form.cleaned_data['nombre']
        apellido = form.cleaned_data['apellidos']
        Empleado.objects.create(
            first_name=nombre,
            last_name=apellido,
            job='1',
            departamento=depa
        )

        return super(NewDepartamentoView, self).form_valid(form)

templates/departamento/lista.html
{% extends 'base.html' %}

{% block title %}
    Lista Departamentos
{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}

    <divc class="grid-containers">
        <div class="grid-x">
            <h1 class="cell">Lista Departamentos</h1>
            <div class="cell">
                <table>
                    <tbody>
                        
                        {% for departamento in departamentos  %}
                        <tr>
                            <td>{{ departamento.name }}</td>
                            <td>{{ departamento.shor_name }}</td>
                            <td>
                                <a class="button warning" href="{% url 'persona_app:empleados_area' departamento.shor_name %}">Ver Empleado</a>
                            </td>
                        </tr> 
                        {% endfor %}
                    </tbody>
                </table>

            </div>
        </div>
    </div>
    
{% endblock content %}
    

templates/departamento/new_departamento.html
{% extends 'base.html' %}


{% block title %}
    Registrar nuevo Departamento
{% endblock title %}


{% block content %}

{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <h3 class="cell">
            Registra Departamento
        </h3>
            <form class="cell callout success grid-x grid-margin-x" method="POST">{% csrf_token %}
                <div class="cell">
                    <h4 class="medium-6 cell">
                        Empleado a Cargo
                    </h4>
                </div>
                    <div class="medium-6 cell">
                        <label>Nombres
                            {{form.nombre}}
                        </label> 
                    </div>
                    <div class="medium-6 cell">
                        <label>Apellidos   
                            {{form.apellidos}}
                        </label>
                    </div>
                <div class="cell">
                    <h4 class="cell">
                        Datos Trabajo
                    </h4>
                </div>
                    <div class="medium-6 cell">
                        <label>Nombre Departamento
                            {{form.departamento}}
                        </label>
                    </div>
                    <div class="medium-6 cell">
                        <label>Nombre corto Departamento
                            {{form.shorname}}
                        </label>
                    </div>
                 <div class="medium-12 cell">
                    <button type="submit" class="success button">Guardar</button>
                </div>                 
            </form>
    </div>
</div>
    
{% endblock content %}
    
 